name: Build FFmpeg for Windows (x86 + x64, many codecs)

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: win64
            msystem: MINGW64
            mingw_arch: x86_64
            ff_arch: x86_64
            prefix: /mingw64
          - name: win32
            msystem: MINGW32
            mingw_arch: i686
            ff_arch: x86
            prefix: /mingw32

    steps:
      - name: Checkout FFmpeg source
        uses: actions/checkout@v4
        with:
          submodules: true

      # 通用依赖（32/64 都有的包）
      - name: Setup MSYS2 (toolchain + common codec libs)
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: >-
            base-devel
            git
            yasm
            nasm
            pkgconf
            mingw-w64-${{ matrix.mingw_arch }}-toolchain
            mingw-w64-${{ matrix.mingw_arch }}-x264
            mingw-w64-${{ matrix.mingw_arch }}-x265
            mingw-w64-${{ matrix.mingw_arch }}-libvpx
            mingw-w64-${{ matrix.mingw_arch }}-aom
            mingw-w64-${{ matrix.mingw_arch }}-opus
            mingw-w64-${{ matrix.mingw_arch }}-libvorbis
            mingw-w64-${{ matrix.mingw_arch }}-lame
            mingw-w64-${{ matrix.mingw_arch }}-libwebp
            mingw-w64-${{ matrix.mingw_arch }}-libtheora
            mingw-w64-${{ matrix.mingw_arch }}-openjpeg2
            mingw-w64-${{ matrix.mingw_arch }}-speex
            mingw-w64-${{ matrix.mingw_arch }}-rtmpdump
            mingw-w64-${{ matrix.mingw_arch }}-srt
            mingw-w64-${{ matrix.mingw_arch }}-vid.stab
            mingw-w64-${{ matrix.mingw_arch }}-libsoxr
            mingw-w64-${{ matrix.mingw_arch }}-zimg
            mingw-w64-${{ matrix.mingw_arch }}-xvidcore
            mingw-w64-${{ matrix.mingw_arch }}-SDL2

      # 只有 64 位才装 fdk-aac 和 vmaf
      - name: "Install extra codecs (64-bit only: fdk-aac, vmaf)"
        if: matrix.name == 'win64'
        shell: msys2 {0}
        run: |
          pacman -S --noconfirm --needed \
            mingw-w64-x86_64-fdk-aac \
            mingw-w64-x86_64-vmaf

      - name: Configure FFmpeg
        shell: msys2 {0}
        run: |
          cd "$GITHUB_WORKSPACE"

          # 用对应前缀下的 toolchain + pkg-config
          export PATH="${{ matrix.prefix }}/bin:$PATH"
          export PKG_CONFIG_PATH="${{ matrix.prefix }}/lib/pkgconfig:$PKG_CONFIG_PATH"

          EXTRA_FLAGS=""
          if [ "${{ matrix.name }}" = "win64" ]; then
            EXTRA_FLAGS="$EXTRA_FLAGS --enable-libfdk-aac --enable-libvmaf --enable-nonfree"
          fi

          ./configure \
            --prefix=${{ matrix.prefix }}/local-ffmpeg \
            --arch=${{ matrix.ff_arch }} \
            --target-os=mingw32 \
            --enable-gpl \
            --enable-version3 \
            --enable-static \
            --disable-shared \
            --disable-debug \
            --enable-libx264 \
            --enable-libx265 \
            --enable-libvpx \
            --enable-libaom \
            --enable-libmp3lame \
            --enable-libopus \
            --enable-libvorbis \
            --enable-libwebp \
            --enable-libtheora \
            --enable-libopenjpeg \
            --enable-libspeex \
            --enable-librtmp \
            --enable-libsrt \
            --enable-libvidstab \
            --enable-libsoxr \
            --enable-libzimg \
            --enable-libxvid \
            --enable-sdl2 \
            --extra-cflags="-O3" \
            --extra-cxxflags="-O3" \
            --extra-ldflags="-static" \
            --pkg-config-flags="--static" \
            $EXTRA_FLAGS

      - name: Build FFmpeg
        shell: msys2 {0}
        run: |
          cd "$GITHUB_WORKSPACE"
          make -j$(nproc)
          make install

      - name: Collect build artifacts
        shell: msys2 {0}
        run: |
          cd "$GITHUB_WORKSPACE"
          mkdir -p dist/${{ matrix.name }}
          cp -a ${{ matrix.prefix }}/local-ffmpeg/bin dist/${{ matrix.name }}/bin
          cp -a ${{ matrix.prefix }}/local-ffmpeg/lib dist/${{ matrix.name }}/lib || true
          cp -a ${{ matrix.prefix }}/local-ffmpeg/include dist/${{ matrix.name }}/include || true

      - name: Upload FFmpeg artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-${{ matrix.name }}
          path: dist/${{ matrix.name }}
